### ISSUE TITLE
sampling at the replay memory

### ISSUE THREAD

**Issue by haiyanyin** [NoListen/ERL#1]
I found there might be a small problem in your way of sampling:
index = self.rng.randint(self.bottom,
                                     self.bottom + self.size - self.phi_length)

When the number of experience exceeds self.size, the value of "self.bottom" will be incremented:
if self.size == self.max_steps:
            self.bottom = (self.bottom + 1) % self.max_steps

But it seems that the sampling should start from index 0, instead of "self.bottom", to uniformly sample from the experience replay.

**Comment by NoListen** [comment]
I think you're right because different random indices may point to the same data in different iterations.
It doesn't matter much actually.
However, I'll try to fix it because I'm going to update the repository.
